"""empty message

Revision ID: 1bc993986076
Revises: f0cbe56c7f2d
Create Date: 2024-10-03 12:12:39.850583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1bc993986076'
down_revision = 'f0cbe56c7f2d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('tipo_precio', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('periodos_espera', sa.Float(), nullable=True),
    sa.Column('incluir_peajes', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('socios')
    # ### end Alembic commands ###
