"""Create direcciones table

Revision ID: 448ffb3697c2
Revises: 458d2a35678f
Create Date: 2024-09-20 20:16:03.662182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '448ffb3697c2'
down_revision = '458d2a35678f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('direcciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('direccion', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=False),
    sa.Column('contacto', sa.String(), nullable=True),
    sa.Column('comentarios', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('direcciones')
    # ### end Alembic commands ###