"""empty message

Revision ID: 88df2626220d
Revises: 8caf5532ea5a
Create Date: 2024-10-01 17:13:13.289461

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '88df2626220d'
down_revision = '8caf5532ea5a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('socios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('tipo_precio', sa.String(length=50), nullable=False),
    sa.Column('precio', sa.Float(), nullable=True),
    sa.Column('periodos_espera', sa.Float(), nullable=True),
    sa.Column('incluir_peajes', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.drop_table('conductores')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conductores',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('apellidos', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('fecha_nacimiento', sa.DATE(), autoincrement=False, nullable=False),
    sa.Column('poblacion', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('ciudad', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('sueldo', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name='conductores_user_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='conductores_pkey')
    )
    op.drop_table('socios')
    # ### end Alembic commands ###
