"""Descripción de los cambios

Revision ID: a9345779081a
Revises: f931e90ebc65
Create Date: 2024-09-27 22:18:33.023808

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a9345779081a'
down_revision = 'f931e90ebc65'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))  # Cambiar a nullable
        # Si necesitas que la columna sea foreign key, pero permite null
        batch_op.create_foreign_key('fk_vehiculos_users', 'users', ['user_id'], ['id'], ondelete='SET NULL')  # Agregar constraint de FK

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehiculos', schema=None) as batch_op:
        batch_op.drop_constraint('fk_vehiculos_users', type_='foreignkey')  # Usar el nombre del constraint
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
