"""Creación de tablas vehiculos y conductores

Revision ID: e74bcb31d553
Revises: af5bc9e60f07
Create Date: 2024-09-24 18:36:25.829847

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e74bcb31d553'
down_revision = 'af5bc9e60f07'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('conductores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('poblacion', sa.String(length=100), nullable=True),
    sa.Column('ciudad', sa.String(length=100), nullable=True),
    sa.Column('sueldo', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vehiculos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('placa', sa.String(length=50), nullable=False),
    sa.Column('remolque', sa.String(length=100), nullable=True),
    sa.Column('costo_km', sa.Float(), nullable=True),
    sa.Column('costo_hora', sa.Float(), nullable=True),
    sa.Column('ejes', sa.Integer(), nullable=True),
    sa.Column('peso', sa.Float(), nullable=True),
    sa.Column('combustible', sa.String(length=50), nullable=True),
    sa.Column('emision', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('placa')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vehiculos')
    op.drop_table('conductores')
    # ### end Alembic commands ###
