"""empty message

Revision ID: fdb42986c77f
Revises: 1d64f781f01b
Create Date: 2024-09-29 09:04:12.841727

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fdb42986c77f'
down_revision = '1d64f781f01b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('poblacion', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conductores', schema=None) as batch_op:
        batch_op.drop_column('poblacion')

    # ### end Alembic commands ###
